apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "quarkus-test"
  description: "quarkus-app"
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/quarkus-test?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web    
    - url: https://devspaces.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/quarkus-test?che-editor=che-incubator/che-idea/next&devfilePath=.devfilev2-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
    - url: https://grafana-route-user-workload-grafana.apps.control-cluster-raffa.demo.red-chesterfield.com/d/AqEG4weWk/error-budget?orgId=1&refresh=5s&var-virtual_service=quarkus-test-stable.-prod.svc.cluster.local&var-time_interval=1h&var-SLO=95&var-latency=1000
      title: SRE Metrics (production)
      icon: web
  annotations:
    'github.com/project-slug': Ruhsi/quarkus-test
    'backstage.io/kubernetes-id': quarkus-test
    'backstage.io/techdocs-ref': dir:.
    'sonarqube.org/project-key': Ruhsi_quarkus-test
    'prometheus.io/alert': ErrorBudgetBurn-critical--prod-quarkus-test,ErrorBudgetBurn-warning--prod-quarkus-test
    'prometheus.io/rule': virtual_service:_prod_quarkus-test:error_rate_1d,virtual_service:_prod_quarkus-test:error_rate_1h,virtual_service:_prod_quarkus-test:error_rate_2h,virtual_service:_prod_quarkus-test:error_rate_30m
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/guests"
  system: quarkus-test